name: we_pray
description: >-
  An app to help you find someone 
  who needs your prayers or to ask
  someone to pray for your needs.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Template
  login_screen: ^0.6.0

  # Utils
  url_launcher: ^5.4.5
  json_serializable: ^3.3.0

  # Formatter
  intl: ^0.16.1

  # State Management
  mobx: ^0.4.0+1
  flutter_mobx: ^0.3.6

  # Data Management
  cloud_firestore: ^0.13.5

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.8.1
  json_annotation: ^3.0.1
  mobx_codegen: ^0.4.0+1

flutter:
  uses-material-design: true

assets:
  - assets/bibles/aa.json
  - assets/bibles/acf.json
  - assets/bibles/nvi.json
